### ISSUE TITLE
How to build ICU shared liberary

### ISSUE THREAD

**Issue by zxckiller** [hunter-packages/icu#2]
Hello，I want to build ICU shared liberary,because static ICU and static Boost can't work together on windows.

I set the BUILD_SHARED_LIBS on ,but it not works.

```
set(BUILD_SHARED_LIBS ON)
hunter_add_package(ICU)
find_package(ICU CONFIG REQUIRED)
```

**Comment by ruslo** [comment]
> I want to build ICU shared liberary

Variable [HUNTER_BUILD_SHARED_LIBS](https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-build-shared-libs) can be used to switch all third parties to shared.

**Comment by zxckiller** [comment]
Solved! Thanks.

**Comment by ruslo** [comment]
> Solved! Thanks.

Closing.
